#pragma once
#include <cassert>
#include <csignal>
#include <cstdio>
#include <functional>
#include <deque>
#include <unordered_map>
#include <vector>
#include <thread>
#include <string>
#include <stdexcept>
#include <typeindex>
#include <typeinfo>
#include <atomic>
#include <mutex>
#include <shared_mutex>
#include <chrono>